### ISSUE TITLE
Won't work with Gnome-Shell 3.4.2

### ISSUE THREAD

**Issue by ghost** [simon04/gnome-shell-extension-weather#107]
I tried to use it with my Debian Testing 64bit with Gnome 3.4.2.
I installed it from source. The entry for the weather-applets appears in gnome-tweak-tool but it's deaktivated and signed with "Not compatible with this Version of gnome-shell".

Im absolutely shure that I have choosen the right branch.

**Comment by ferdnyc** [comment]
What does the "shell-version" line in the extensions's `metadata.json` contain? (It's in the extension install directory, which is probably one of...)
- `/usr/share/gnome-shell/extensions/weather@...`
- `/usr/local/share/gnome-shell/extensions/weather@...`
- `$HOME/share/gnome-shell/extensions/weather@...`

My installed build off the gnome-3.4 branch, which works in Fedora 17's 3.4.1, contains:
`"shell-version": [ "3.1.90", "3.1.91", "3.1.92", "3.2", "3.3", "3.3.90", "3.3.92", "3.4" ],`

...But regardless, what happens if you manually add `, "3.4.2"` to the end of that list (whatever it is currently)?

**Comment by ghost** [comment]
Thank you for your answer,
my "shell-version"-line ist looking the same as yours.
But anyway, now I think the problem is on my side. I only installed a "Mini-Gnome" without any recommends and suggests on my PC. It seems, something is missing there, because today I installed the extension on my Laptop (also Debian Testing but with the complete Gnome 3.4 Desktop) and there, everything works fine.
So I had to find out now, where the relevant difference is.

The problem is obviously not related to the extension.
Sorry for the inconvenience.
