### ISSUE TITLE
wind direction arrows are inverted?

### ISSUE THREAD

**Issue by whyoh** [simon04/gnome-shell-extension-weather#110]
i think if you're using arrow graphics to represent wind direction (rather than saying "NE", "WSW" etc) the arrows should point in the direction the wind is blowing <i>towards</i> rather than pointing to where the wind is coming from.

so if the wind direction is "N" (from the north) the arrow should point south (down).

i've tried changing the last line of get_compass_direction accordingly:

``` javascript
return directions[Math.round((180 + deg) / 45) % directions.length];
```

that seems to do the trick.  sorry no pull request - i've not really got the hang of those yet.  can do one if you really need it though.

**Comment by ferdnyc** [comment]
weather.com agrees, that's exactly how they represent it. See http://www.weather.com/weather/right-now/

I was going to generate a pull request for this (giving you credit), but then I realized... I'm confused. Where _are_ we using arrows to represent the wind direction? I don't see that anywhere in the code. Nor do I see arrows on my installed copy of the extension.

Are you sure the version you're running is built off this repo? Perhaps it's someone else's code. (In which case, they should get the bug — we can't fix it here, because AFAICT we don't have the arrow code to begin with.)

**Comment by whyoh** [comment]
ah, i see.  i'm using a package in fedora fusion repo.  looks like they're either using an old version or they've patched it to use unicode arrow characters in place of the N/NE/E etc letters.  sorry - i'll track it down there.

thanks for looking at it though!  :-)

**Comment by whyoh** [comment]
for completeness:

it's Neroth's branch i'm using.  and they've fixed this problem a month ago - and fedora fusion picked up that update a couple of weeks back.  #shouldhavejustdoneanupdate

**Comment by ferdnyc** [comment]
Heh! Well, no harm done, the important thing is you tracked it down. Thanks for letting us know the resolution, too.

Actually, I'm glad this came up, because the wind-direction arrows do sound like a nice feature to have... I'm thinking I might go raid Neroth's repo for that code! ;-) (Though, most likely, my patch would display arrows _along with_ the textual direction labels, rather than _instead of_... as weather.com and most other services seem to do. The arrows are a nice touch, but no need to make people decode pointers when reading "NNE" or "SW" is so much quicker & easier.)

Anyway, like I said, all's well that ends well. Glad you got it sorted out!

**Comment by whyoh** [comment]
yeah, i like the arrows too.  fwiw BBC weather only has arrows.  looks like Neroth's added a setting for displaying either arrows or letters - guess we could have a 'both' option. .. .and a 'none' option.  personally i'd prefer a nice svg arrow rendered at the angle provided by yahoo, rather than restricting to eight unicode characters.  that way the arrow would be providing useful information even beyond the 16 directions of WSW etc - potentially, at least.

**Comment by ferdnyc** [comment]
Heh. Yeah, that came to me as I was lying down to sleep last night.
"Wait... there's no Unicode arrow symbol for 'ENE', is there??" :-)
