### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by sasanrose** [simon04/gnome-shell-extension-weather#48]
I installed the extension and activated it trough gnome-tweak-tool then:

gsettings set org.gnome.shell.extensions.weather woeid IRXX0018

i even used:

gsettings set org.gnome.shell.extensions.weather woeid "'IRXX0018'"

But  i just receive:

Please Wait
Loading

And nothing changes.

**Comment by simon04** [comment]
I cannot reproduce. Please test network settings, update to newest version.

**Comment by fishears** [comment]
I also have this issue. The extension permanently displays the loading symbol and three dots. I use Gnome 3.2.1 on OpenSuse 12.1 WOEID is UKXX01104. It worked on Fedora 16 though...

**Comment by fishears** [comment]
Ah.. after reading your main page I spotted that WOEID should be 4 Alpha, 4 Numeric - my code had 5 Numeric for some reason. All works when I enter UKXX0104!!! :D

**Comment by ferdnyc** [comment]
Actually, it's funny. I ended up spending a couple of HOURS slogging through Yahoo's info on the WOEID, as a result of some confusion due to [issue #47](https://github.com/simon04/gnome-shell-extension-weather/issues/47).

A WOEID is actually a 32-bit integer value [[ref](http://developer.yahoo.com/geo/geoplanet/guide/concepts.html)], so anything using the AAAA#### format is **not** technically a valid WOEID. However, the weather extension is not _actually_ using WOEIDs, it seems, despite the label in the configurator. What it's using are the location IDs accepted by the Weather API, which means either weather station "location codes" assigned(?) by weather.com, and used in the old weather panel applet from GNOME2, or (at least in the US) postal ZIP codes.

Compare the following two docs: [Old Weather API Doc (Archived)](http://developer.yahoo.com/weather/archive.html) ...vs... [Current Weather API Doc](http://developer.yahoo.com/weather/)

In the old Weather API, you could enter either zip code or location ID, which is the same thing we accept.  (I have no idea how, or if, it worked for non-US users, w/r/t postal codes.)

In the new Weather API, which takes WOEID codes, you're instructed to look up your WOEID on the Yahoo Weather page — it appears in the URL of your results. I'll use my own as an example.
- If I enter my ZIP code into the configurator, it shows my city as "Bronx" (correct), and the link leads to:
  http://weather.yahoo.com/united-states/new-york/bronx-12589314/
  - So, the WOEID for my neighborhood (ZIP 10454) is 12589314.
- If I enter USNY0998 into the configurator, I get weather for "New York/Central Park" (not wrong, though slightly different) and the link leads to:
  http://weather.yahoo.com/united-states/new-york/central-park-23505566/
  - So, that WOEID is 23505566
- If I search for "New York, NY" on the Yahoo Weather page, I get taken to:
  http://weather.yahoo.com/united-states/new-york/new-york-2459115/
  - This shows me the same weather as the previous entry, although the WOEID this time is 2459115

If I plug any of those all-numeric WOEIDs, or any of the ones given as examples in the docs, into the configurator's "WOEID" field, the weather extension fails to obtain data. It'll stay frozen with the previous data, if there is any, otherwise it'll sit there forever stuck in "..." mode.

So, I think labeling the field "WOEID" is technically not correct; it should be "Location ID". If you have a weather location code in the AAAA0000 format that's correct for your location, then the data returned should be valid. Or you can use a postal code (if applicable).

And as I learned the very hard way, anytime the data doesn't match up to the location, it's most probably a manifestation of issue #47 and **NOT** a problem with the location code.
